package org.alter.plugins.content.skills.slayer

enum class SlayerMonster(
    val level: Int,
    val ids: List<String>,
    val superiorId: String?
) {
    CRAWLING_HAND(5, listOf("npc.crawling_hand_448"), "npc.crushing_hand"),
    CAVE_BUG(7, listOf("npc.cave_bug"), null),
    CAVE_CRAWLER(10, listOf("npc.cave_crawler_406"), "npc.chasm_crawler"),
    BANSHEE(15, listOf("npc.banshee_414"), "npc.screaming_banshee"),
    CAVE_SLIME(17, listOf("npc.cave_slime"), null),
    ROCKSLUG(20, listOf("npc.rockslug_421"), "npc.giant_rockslug"),
    DESERT_LIZARD(22, listOf("npc.desert_lizard_459"), null),
    COCKATRICE(25, listOf("npc.cockatrice_419"), "npc.cockathrice"),
    PYREFIEND(30, listOf("npc.pyrefiend_3139"), "npc.flaming_pyrelord"),
    MOGRE(32, listOf("npc.mogre_2592"), null),
    HARPIE_BUG_SWARM(33, listOf("npc.harpie_bug_swarm"), null),
    WALL_BEAST(35, listOf("npc.wall_beast"), null),
    KILLERWATT(37, listOf("npc.killerwatt_469"), null),
    MOSS_GIANT(39, listOf("npc.moss_giant"), null),
    BASILISK(40, listOf("npc.basilisk_122"), "npc.monstrous_basilisk"),
    TERRORDOG(40, listOf("npc.terror_dog_6473"), null),
    FEVER_SPIDER(42, listOf("npc.fever_spider_626"), null),
    INFERNAL_MAGE(45, listOf("npc.infernal_mage_443"), "npc.malevolent_mage"),
    BRINE_RAT(47, listOf("npc.brine_rat_4501"), null),
    BLOODVELD(50, listOf("npc.bloodveld_484"), "npc.insatiable_bloodveld"),
    JELLY(52, listOf("npc.jelly_437"), "npc.vitreous_jelly"),
    TUROTH(55, listOf("npc.turoth_426"), "npc.spiked_turoth"),
    ZYGOMITE(57, listOf("npc.zygomite"), null),
    CAVE_HORROR(58, listOf("npc.cave_horror_1047"), "npc.cave_abomination"),
    ABERRANT_SPECTRE(60, listOf("npc.aberrant_spectre_2"), "npc.abhorrent_spectre"),
    SPIRITUAL_RANGER(63, listOf("npc.spiritual_ranger"), null),
    WYRM(62, listOf("npc.wyrm_8610"), null),
    DUST_DEVIL(65, listOf("npc.dust_devil_423"), "npc.choke_devil"),
    KURASK(70, listOf("npc.kurask_410"), "npc.king_kurask"),
    SKELETAL_WYVERN(72, listOf("npc.skeletal_wyvern_465"), null),
    GARGOYLE(75, listOf("npc.gargoyle_412"), "npc.marble_gargoyle"),
    NECHRYAEL(80, listOf("npc.nechryael_11"), "npc.greater_nechryael"),
    ABYSSAL_DEMON(85, listOf("npc.abyssal_demon_415"), "npc.greater_abyssal_demon"),
    DRAKE(84, listOf("npc.drake_8612"), "npc.guardian_drake"),
    DARK_BEAST(90, listOf("npc.dark_beast_4005"), "npc.night_beast"),
    SMOKE_DEVIL(93, listOf("npc.smoke_devil_498"), "npc.nuclear_smoke_devil"),
    HYDRA(95, listOf("npc.hydra_8609"), "npc.colossal_hydra")
}