package gg.rsmod.plugins.api.cfg

object Varbits {

    const val ALL_SETTINGS_TAB = 9656

    // Activities
    const val ACTIVITIES_HITSPLAT_TINTING = 10236
    const val ACTIVITIES_SHOW_BOSS_HEALTH_OVERLAY = 12389
    const val ACTIVITIES_LAST_MAN_STANDING_FOG_COLOUR = 11865

    // Audio
    const val AUDIO_MUSIC_AREA_MODE = 12233
    const val AUDIO_MUSIC_UNLOCK_MESSAGE = 10078

    // Chat
    const val CHAT_FRIENDS_LOGIN_LOGOUT_MESSAGES = 12274
    const val CHAT_HIDE_PRIVATE_CHAT_WHEN_CHATBOX_IS_HIDDEN = 4089
    const val CHAT_PRECISE_TIMING = 11866
    const val CHAT_SEPARATING_HOURS = 11890
    const val CHAT_COLLECTION_LOG_NOTIFICATION = 11959
    const val CHAT_LOOT_DROP_VALUE = 5400
    const val CHAT_LOOT_DROP_ENABLE = 5399
    const val CHAT_LOOT_DROP_VALUE_INPUT = 9647
    const val CHAT_UNTRADEABLE_NOTIFICATION = 5402
    const val CHAT_FILTER_BOSS_KILL_COUNT = 4930
    const val CHAT_COMBAT_ACHIEVEMENT_FAILURE = 12454
    const val CHAT_COMBAT_ACHIEVEMENT_FAILURE_REPEAT = 12457
    const val CHAT_COMBAT_ACHIEVEMENT_COMPLETION_REPEAT = 12456
    const val CHAT_CHATBOX_MODE_AUTOMATIC = 13120

    // Keybinds
    const val ATTACK_KEYBIND = 4675
    const val PRAYER_KEYBIND = 4680
    const val SETTINGS_KEYBIND = 4686
    const val SKILLS_KEYBIND = 4676
    const val MAGEBOOK_KEYBIND = 4682
    const val EMOTES_KEYBIND = 4687
    const val QUEST_KEYBIND = 4677
    const val FRIENDS_KEYBIND = 4684
    const val CLAN_KEYBIND = 4683
    const val INVENTORY_KEYBIND = 4678
    const val PROFILE_KEYBIND = 6517
    const val MUSIC_KEYBIND = 4688
    const val EQUIPMENT_KEYBIND = 4679
    const val LOGOUT_KEYBIND = 4689

}