package gg.rsmod.game.service.world

import gg.rsmod.game.fs.StructDefinitions

class Setting(struct : StructDefinitions) {
    val IS_DESKTOP_PARAM = 739;
    val IS_MOBILE_PARAM = 740;
    val IS_NON_IRONMAN_PARAM = 741;
    val IS_IRONMAN_PARAM = 742;
    val ID_PARAM = 1077;
    val TYPE_PARAM = 1078;
    val PRE_REQUIREMENTS_ENUM_ID_PARAM = 1080;
    val PRE_REQUIREMENTS_VALUES_ENUM_ID_PARAM = 1081;
    val PRE_REQUIREMENTS_INVERSED_ENUM_ID_PARAM = 1082;
    val PRE_REQUIREMENTS_INVERSED_VALUES_ENUM_ID_PARAM = 1083;
    val NAME_PARAM = 1086;
    val SEARCH_KEYWORDS_PARAM = 1088;
    val DROPDOWN_ENTRIES_PARAM = 1091;
    val DROPDOWN_ENTRIES_MOBILE_PARAM = 1092;
    val SLIDER_NOTCH_COUNT_PARAM = 1101;
    val IS_SLIDER_TRANSMITTED_PARAM = 1105;
    val HAS_CUSTOM_REQUIREMENTS_PARAM = 1115;
    val HAS_TOGGLE_INVERSED_PARAM = 1084;
    val CHOOSE_TRANSMIT_PARAM = 1085;
    val MOBILE_NAME_PARAM = 1087;
    val DESCRIPTION_PARAM = 1096;
    val KEYBIND_SPITE_PARAM = 1098;
    val KEYBIND_SPRITE_SIZE_COORDGRID_PARAM = 1099;
    val SLIDER_SECTORS_PARAM = 1102;
    val SLIDER_SECTOR_TEXT_ENUM_ID_PARAM = 1103;
    val SLIDER_CUSTOM_ON_OP_PARAM = 1106;
    val SLIDER_CUSTOM_SETPOS_PARAM = 1107;
    val IS_SLIDER_DRAGGABLE_PARAM = 1108;
    val SLIDER_DEADZONE_PARAM = 1109;
    val SLIDER_DEADTIME_PARAM = 1110;
    val SLIDER_INPUT_SINGULAR_PARAM = 1111;
    val SLIDER_INPUT_PLURAL_PARAM = 1112;
    val SLIDER_INPUT_ZERO_PARAM = 1113;
    val SLIDER_OP_CHECKER_MESSAGE_PARAM = 1116;
    val SLIDER_MOBILE_OP_CHECKER_MESSAGE_PARAM = 1117;
    val HAS_COLLAPSIBLE_INFOBOX_PARAM = 1118;
    val HIDE_DESCRIPTION_PARAM = 1119;
    val IS_ENHANCED_CLIENT_PARAM = 1157;
    val CUSTOM_NAME_EXTRA_TEXT_PARAM = 1158;
    val IS_MOBILE_ALWAYS_ENABLED_PARAM = 1186;
    val HAS_CUSTOM_CHECK_PARAM = 1229;
    val DEFAULT_COLOUR_PARAM = 1230;
    val IS_NON_DESKTOP_ONLY_PARAM = 1271
    val IS_LEAGUE_WORLD_ONLY_PARAM = 1272
    val IS_LEAGUE_ENHANCED_CLIENT_ONLY_PARAM = 1273
}